name: Publish on Docker

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v1
      - name: Setting Image Name
        run: |
          IMAGE_NAME=oddity:$(date +%s)
          echo $IMAGE_NAME
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Install Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build and push
        run: |
          docker buildx build -f Dockerfile.arm --push \
            --tag "${{secrets.DOCKERHUB_USER}}/holy_sticker_lib:${GITHUB_SHA::8}" \
            --tag "${{secrets.DOCKERHUB_USER}}/holy_sticker_lib:latest" \
            --platform linux/arm/v7 .
